language: ruby
rvm:
- 2.3.1
env:
  global:
  - TRAVIS_NODE_VERSION="v8.9.4"
  - GH_REF=github.com/IFRCGo/sims-website.git
  - DEPLOY_BRANCH=publish
  - secure: YXKOlKUzMmm0a3PiS5F13KR0fEkFQ99CEu2eiQ0QRQt3bENcYZejdmnXRx1DORIKKP5zlmAmworDquDubGf8GZA878JDSyUkEOrIDa1jo+EOAuceDUVilSQ5EHcFtT5xz2ZXP8C7hyr9oHt5kWGDCDz1fjVmK/iuDQI0BuernTQggqT/9vZwlmEYSZLizSJtY1nCPIm4X/++q026hv6lzsRuIcVNHEnsqJMUpL7+H0k9rDp/2aOwhh1isdELlIIbzn/cnFigzoOra5ecizTFz9BovECWw/O/UbufGxIUZU4N3pHpqZvw/oiKwLXrjnhl5dYWz/NCMbT4Mpejxs0H9B8fo+QIm2K1r47O0y8SqZk2hrnY1sf63q/Et6Wa2fuVzsdfIo5SNYLxlzv9I+w/shGZfSMkpf9wV2CceRdY2AdQDQVJCeijvozAOaB9z+L+HCm/VSgAUMEEdgYW+gMRp1zRJn7glxOFij22+NxPZ0ykhUCfVX6pAbQhKserZox4bkQ7kCzzK/ztQ/7yuRVzXIH0/k7UFHObavl/FbZXzHeJt5Xb5HSZyAL3XfiFODGr2/+IxK/ra8RxQffZf+Ca968Vxi/CeI7t0GT3Q/bu30l0inKNJpeeCrTEzbt0nN6b3Lz7KoViKpCzCP1yM2/4g3wSMaPk8uPRgMnR9AyxztI=
before_install:
- chmod +x ./.build_scripts/deploy.sh
before_script:
- ". $HOME/.nvm/nvm.sh"
- nvm install $TRAVIS_NODE_VERSION
- nvm use $TRAVIS_NODE_VERSION
- npm install -g gulp
- npm install
script: gulp prod
after_success:
- "./.build_scripts/deploy.sh"
